contact_links:
  - name: ğŸ’¡ Feature Request
    url: https://github.com/ptarmiganlabs/butler-cw/discussions/new
    about: Share ideas for new features
  - name: â“ Question
    url: https://github.com/ptarmiganlabs/butler-cw/discussions/new
    about: General questions
